### ISSUE TITLE
Empty event list in iOS 13.1.2

### ISSUE THREAD

**Issue by MarkusTiede** [digital-sustainability/event-app-mobile#1]
When opening the app on iOS 13.1.2 the upcoming and past event list is empty.

**Comment by Elbarto9** [comment]
Thank you for reporting the issue.

It was a iOS 13 compatibility issue: We fixed it by upgrading the listview & cardview plugins.

**Comment by MarkusTiede** [comment]
Agreeing: version 1.6 is now working - thanks for the immediate fix!
